### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by j-patel** [labai/opa#1]
I have two questions:

1) Is it possible to use this project with Ant instead of Maven? How? I can only use Ant for some reason.

2) Once I am able to use this, how can I make a call to internal procedure?

Thank you.

**Comment by labai** [comment]
1. You need to add jar files to your Java project:
 The opa jar can be compiled or found in https://mvnrepository.com/artifact/com.github.labai/opa .
 In addition you need [commons-pool2](https://mvnrepository.com/artifact/org.apache.commons./commons-pool2/2.4.2) and [slf4j-api](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.12).
 And also you will need o4glrt.jar (from OpenEdge installation).

2. Internal procedures call is not supported. Is is planned to use in staleless/statefree mode, when AppServer agent is not reserved for client and each AppServer call is independent.
In some cases it may be workaround to write on server wrapper procedure, which can load required persistent procedure, then call it's internal procedure and after then may destroy that persistent procedure.
